use_frameworks!

platform :ios, '9.0'

target 'HLBluetoothTool_Example' do
  pod 'HLBluetoothTool', :path => '../'

  target 'HLBluetoothTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
